export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const LAY_THONG_TIN_USER = "LAY_THONG_TIN_USER";
export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG_KEYWORD =
  "LAY_DANH_SACH_NGUOI_DUNG_KEYWORD";
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG = "LAY_DANH_SACH_LOAI_NGUOI_DUNG";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";

// Modal
export const OPEN_MODAL_USER = "OPEN_MODAL_USER";
export const CLOSE_MODAL_USER = "CLOSE_MODAL_USER";
